use_frameworks!

platform :ios, '9.0'

target 'SDWebImageVideoCoder_Example' do
  pod 'SDWebImageVideoCoder', :path => '../'

  target 'SDWebImageVideoCoder_Tests' do
    inherit! :search_paths

    
  end
end
